In [ ]:
from sklearn.datasets import make_blobs
from matplotlib import pyplot
import pandas as pd

data,target=make_blobs(n_samples=30000000,n_features=5,centers=3,cluster_std=[1.0,3.0,2.0])

#在2D图中绘制样本，每个样本颜色不同
# pyplot.scatter(data[:,0],data[:,1],c=target);
# pyplot.show()

In [2]:
print(data)
print(target)

[[ -5.40009279  -4.11644703   7.12807757  -2.16215896   3.58341238]
 [ -3.14793296 -11.24984487  -0.98783922   1.66551482  -7.14110339]
 [ -8.55504316   5.38988636  10.14854941  11.28769453  -8.04489852]
 ...
 [  1.53536919  -4.50207395  -1.64054595  -0.37292671  -9.59024888]
 [ -3.46579484  -4.47169211   5.79707137  -2.27052318   5.7031234 ]
 [ -6.95270758   2.53640553  10.5186124    9.71156249  -6.51697644]]
[0 1 2 ... 1 0 2]


In [17]:
type(data)

numpy.ndarray

In [3]:
data3 = pd.DataFrame(data)

In [4]:
data3

0          1          2          3         4
0        -5.400093  -4.116447   7.128078  -2.162159  3.583412
1        -3.147933 -11.249845  -0.987839   1.665515 -7.141103
2        -8.555043   5.389886  10.148549  11.287695 -8.044899
3        -4.599301  -3.900174   7.296054  -0.938264  6.355937
4         3.248170  -6.228061   7.632163   4.715192 -8.501892
...            ...        ...        ...        ...       ...
19999995 -4.926581 -10.283395   1.853870   2.445352  1.923209
19999996  1.075652 -11.251988   2.385286   3.287826 -7.671585
19999997  1.535369  -4.502074  -1.640546  -0.372927 -9.590249
19999998 -3.465795  -4.471692   5.797071  -2.270523  5.703123
19999999 -6.952708   2.536406  10.518612   9.711562 -6.516976

[20000000 rows x 5 columns]

In [5]:
data3.to_csv("data3.csv", header=None, index=None, index_label=None)